### ISSUE TITLE
on_open() missing 1 required positional argument: 'ws'

### ISSUE THREAD

**Issue by MathiasGilson** [sacOO7/socketcluster-client-python#16] opened 2018-08-29 19:37 UTC
Need to update dependency websocket-client <= 0.48

I'll send a PR

**Comment by sacOO7** [comment] 2018-08-30 12:30
Hi @MathiasGilson, thank you for the information. Will look into it for sure 👍

**Comment by sacOO7** [comment] 2018-09-09 14:42
I am not able to reproduce the issue. Can please add details for the same in here?

**Comment by hacka007** [comment] 2018-09-11 08:18
Same Issue here:
```
websocket   : ERROR    error from callback <bound method socket.on_open of <socketclusterclient.Socketcluster.socket object at 0x7f7d2216ea90>>: on_open() missing 1 required positional argument: 'ws'
  File "/usr/local/lib/python3.7/site-packages/websocket/_app.py", line 333, in _callback
    callback(*args)
websocket   : ERROR    error from callback <bound method socket.on_message of <socketclusterclient.Socketcluster.socket object at 0x7f7d2216ea90>>: on_message() missing 1 required positional argument: 'message'
  File "/usr/local/lib/python3.7/site-packages/websocket/_app.py", line 333, in _callback
    callback(*args)
websocket   : ERROR    error from callback <bound method socket.on_message of <socketclusterclient.Socketcluster.socket object at 0x7f7d2216ea90>>: on_message() missing 1 required positional argument: 'message'
  File "/usr/local/lib/python3.7/site-packages/websocket/_app.py", line 333, in _callback
    callback(*args)
websocket   : ERROR    error from callback <bound method socket.on_close of <socketclusterclient.Socketcluster.socket object at 0x7f7d2216ea90>>: on_close() missing 1 required positional argument: 'ws'
  File "/usr/local/lib/python3.7/site-packages/websocket/_app.py", line 333, in _callback
    callback(*args)
```

I think the changes from websocket-client  0.48 to 0.49 create the issue but I'm not sure

**Comment by MathiasGilson** [comment] 2018-09-11 22:24
@sacOO7 you need to reinstall your package in an environment without websocket-client installed, you can try in a docker container. I guess you have a version of websocket-client <= 0.48 installed on your machine that prevents you from reproducing the issue.

**Comment by MathiasGilson** [comment] 2018-09-12 12:19
@hacka007 if you need a quick fix you can install `websocket-client<=0.48` before installing `socketcluster-client-python`, as no version of `websocket-client` is specified in the `socketcluster-client-python` package, this later will use the version 0.48 of `websocket-client` and this will work

`pip3 install 'websocket-client<=0.48'` should do the job

**Comment by sacOO7** [comment] 2018-09-12 16:32
Hi @MathiasGilson,Thanks for the solution. Little busy those days...  Will be pushing solution soon

**Comment by sacOO7** [comment] 2018-09-25 15:12
Hi @MathiasGilson , @hacka007 I have merged the PR and updated release for the client. The library should now work for you guys.

**Comment by MathiasGilson** [comment] 2018-09-26 11:51
Great ! thanks

**Comment by sacOO7** [comment] 2018-09-26 16:57
Hey, you can try downloading latest version. Do let me know if you are facing any more of those problems.

**Closed as completed by sacOO7** 2018-09-26 16:57 UTC
