### ISSUE TITLE
Logging/PrintOut

### ISSUE THREAD

**Issue by broble1** [sacOO7/socketcluster-client-python#6] opened 2017-10-16 17:55 UTC
What settings can I use or where can I modify the source code to turn off console printing for every message received?

**Comment by lhayhurst** [comment] 2018-01-01 07:49
Yeah, it would better to let the client control this :-)

The library is setting the logging level on line 10 of Socketcluster.py. You can comment that out, and then set the logging level in your own code using the line you commented out.

**Comment by brunoalano** [comment] 2018-04-03 14:48
You can just overwrite the Global Logger. Based on [1], and since `socketcluster-client-python` its invoking `logging.basicConfig`, doing this solve the issue:

```python
import logging
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.CRITICAL)
from socketclusterclient import Socketcluster
```

[1] https://docs.python.org/3/library/logging.html#logging.basicConfig

**Comment by sacOO7** [comment] 2018-07-09 14:55
Hi @broble1 , @lhayhurst , @brunoalano . Sorry, it's little late. But, the issue is resolved in the latest release of library. Try downloading latest version.... You should even be able to modify the logging settings by getting logger instance.

**Comment by sacOO7** [comment] 2018-09-25 03:10
Hi @broble1 , @lhayhurst  @brunoalano , since there are no updates, I will close the issue. Feel free to raise more issues if any problem persists.

**Closed as completed** 2018-09-25 03:11 UTC
